# Generated by Django 5.0.6 on 2024-07-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='año',
            field=models.TextField(max_length=4, null=True),
        ),
    ]
