# Generated by Django 5.0.6 on 2024-07-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0002_car_año'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='año',
            new_name='year',
        ),
    ]
